name: publish
on: [push]
jobs:
publish-go-docker-demo-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
- name: Build the go-docker-demo Docker image
run: |
       docker build . --tag ghcr.io/deselikem/go-docker-demo-gcr-demo:latest
       docker run ghcr.io/deselikem/go-docker-demo-gcr-demo:latest
       docker push ghcr.io/deselikem/go-docker-demo-gcr-demo:latest